version: "3.9"
services:
  db:
    container_name: geopol-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: geopol
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: 